package OOPConcepts.ExceptionalHandling.example1;

public class App {
    public static void main(String args[]) throws ArithmeticException{
        int i = 2;
        int j  = 0;

        System.out.println(i/j);

        System.out.println("Hey! this is after exception.");

    }
}
